In [1]:
import numpy as np

In [2]:
#integer array
np.array([1,4,2,3,4])

array([1, 4, 2, 3, 4])

In [3]:
a = 12
a

12

In [4]:
#float array
np.array([1,4,2,3,4], dtype = 'float32')

array([1., 4., 2., 3., 4.], dtype=float32)

In [5]:
#multidimension array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# 3x5 array filled value 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])