In [1]:
import numpy as np

In [2]:
#integer array
np.array([1,4,2,3,4])

array([1, 4, 2, 3, 4])

In [3]:
a = 12
a

12

In [4]:
#float array
np.array([1,4,2,3,4], dtype = 'float32')

array([1., 4., 2., 3., 4.], dtype=float32)

In [5]:
#multidimension array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# 3x5 array filled value 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [1]:
hello world

SyntaxError: invalid syntax (<ipython-input-1-22596363b3de>, line 1)

In [2]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() functi
np.arange(0, 20, 2)

NameError: name 'np' is not defined

In [3]:
import numpy as np
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
#create array evenly space (tao arr co cac phan tu cach deu) beetween 0 .. 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
#3x3 array, random value between 0..1
# phan bo dong deu
np.random.random((3,3))

array([[0.56598438, 0.30506703, 0.8110902 ],
       [0.46923841, 0.50210004, 0.32957601],
       [0.90593248, 0.9752003 , 0.2868235 ]])

In [2]:
import numpy as np
# 3x3 arr, random value, phan bo ko dong deu
# trung binh la 0, do lech  1
np.random.normal(0,1, (3,3))

array([[ 1.76957327, -0.90760171, -0.39840074],
       [-0.76983684, -0.80819983,  0.37690346],
       [-0.66236043,  0.11408126, -1.54935197]])

In [3]:
# 3x3, random value trong khoang 0, 10
np.random.randint(0,10,(3,3))

array([[6, 5, 4],
       [7, 8, 8],
       [2, 3, 6]])

In [4]:
#ma tran don vi - identity matrix - ma tran vuong co tat ca phan tu duong cheo = 1, phan tu con lai = 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [6]:
# hàm empty tạo ra dãy với giá trị được chọn ngẫu nhiên và phụ thuộc vàotrạng thái của bộ nhớ
np.empty((3,1))

array([[1.],
       [1.],
       [1.]])

In [7]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))# Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x4 = np.random.randint(10,size = 6)

In [11]:
x4

array([4, 3, 4, 4, 8, 4])

In [12]:
np.random.seed(0)
np.random.randint(3,size = 2)

array([0, 1])

In [13]:
np.random.seed(0) #hat giong 0
x1 = np.random.randint(10,size = 4)
np.random.seed(0)
x4 = np.random.randint(10, size = 4)
x1, x4

(array([5, 0, 3, 3]), array([5, 0, 3, 3]))

In [14]:
np.random.seed(1) #hat giong 1
x1 = np.random.randint(10,size = 4)
np.random.seed(1)
x4 = np.random.randint(10, size = 4)
x1, x4

(array([5, 8, 9, 5]), array([5, 8, 9, 5]))

In [17]:
# truy cap phan tu
print(x3)
x3[2,-1]

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


array([9, 4, 4, 6, 4])

In [19]:
# access subarray = slicing
x3[::-1]

array([[[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]]])

In [22]:
# subarray
x3[::2,::3,::1 ]

array([[[8, 1, 5, 9, 8],
        [1, 3, 3, 3, 7]],

       [[4, 9, 8, 1, 1],
        [9, 4, 4, 6, 4]]])

In [23]:
# subarr = arr
x3[::-1,::-1,::-1]

array([[[4, 6, 4, 4, 9],
        [5, 3, 0, 2, 7],
        [6, 3, 9, 9, 7],
        [1, 1, 8, 9, 4]],

       [[1, 4, 8, 6, 5],
        [5, 4, 0, 0, 2],
        [7, 2, 3, 7, 4],
        [0, 9, 9, 1, 0]],

       [[7, 3, 3, 3, 1],
        [8, 3, 2, 0, 5],
        [3, 0, 3, 4, 9],
        [8, 9, 5, 1, 8]]])

In [30]:
# single row, column
x3[::-1,::-1,-2] # column cuoi

array([[6, 3, 3, 1],
       [4, 4, 2, 9],
       [3, 3, 0, 9]])

In [32]:
import numpy as np
#access row, column
x3[0:2,0:3,-1 ]

array([[8, 3, 8],
       [0, 7, 5]])

In [34]:
#reshape = size
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
grid.size

9

In [37]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [38]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [39]:
x.reshape((1,3))

array([[1, 2, 3]])

# concat and split

In [2]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5])
np.concatenate([x,y])

array([1, 2, 3, 4, 5])

concatenate along the second axis

In [6]:
grid = np.array([[1,2,3],
                 [3,2,1]]) 
np.concatenate([grid, grid], axis = 1)#axis = 0 se ra mang (4x3), axis = 1 ra mang (2x6)

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

mix array

In [7]:
x = np.array([1,2,3])
y = np.array([[1,3,4],[2,4,6]])

In [8]:
np.vstack([x,y])

array([[1, 2, 3],
       [1, 3, 4],
       [2, 4, 6]])

In [9]:
np.vstack([y,x])

array([[1, 3, 4],
       [2, 4, 6],
       [1, 2, 3]])

In [14]:
z = np.array([[2,3],[4,2]])

In [15]:
np.hstack([y,z])

array([[1, 3, 4, 2, 3],
       [2, 4, 6, 4, 2]])

split

In [16]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [18]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
upper, lower = np.vsplit(grid, [3]) #vertical split
print(upper)
print(lower)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [26]:
left, right = np.hsplit(grid, [1]) #horizontal split
print(left)
right

[[ 0]
 [ 4]
 [ 8]
 [12]]


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

# Ufuncs

### Array arithmetic

In [31]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # chia lay nguyen


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [32]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [33]:
-(0.5*x + 1) ** x

array([ -1.   ,  -1.5  ,  -4.   , -15.625])

In [34]:
# x+2
np.add(x,2)

array([2, 3, 4, 5])

In [36]:
# absolute
x = np.array([-2, -1, 0, 1, 2])
print(abs(x))
print(np.abs(x))
np.absolute(x)

[2 1 0 1 2]
[2 1 0 1 2]


array([2, 1, 0, 1, 2])

In [37]:
# abs with complex data
x = np.array([5+12j, 12-5j, 3+4j])
np.abs(x)

array([13., 13.,  5.])

In [38]:
# ham` luong giac - trigono metric func
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [41]:
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [42]:
x = [-1,0,1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [43]:
 x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [44]:
 x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


## Specialized ufuncs