In [1]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
A = array.array(L)

TypeError: array() argument 1 must be a unicode character, not list

In [3]:
import numpy as np


In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
#cat mang
temp =arr[:3,::2]
print ("Mảng với 3 hàng đầu và cột xen kẽ (cột số 0 và số 2):\n", temp)
 
# Dùng chỉ mục với mảng số nguyên
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)
 
# Mảng sử dụng các điều kiện để lấy phần tử
cond = arr > 0
temp = arr[cond]
print ("\nCác phần tử lớn hơn không là:\n", temp)

Mảng với 3 hàng đầu và cột xen kẽ (cột số 0 và số 2):
 [[-1.   0. ]
 [ 4.   6. ]
 [ 2.6  7. ]]

Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]

Các phần tử lớn hơn không là:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [7]:
x = np.array([3,2,1])

In [8]:
total = 0
for i in range(x.size()):
    total += x[i]

TypeError: 'int' object is not callable

In [9]:
total = int(0)

In [10]:
for i in range(x.size()):
    total+= x[i]

TypeError: 'int' object is not callable

In [11]:
x[1]

2

In [12]:
type(x[0])

numpy.int32

In [13]:
type(x)

numpy.ndarray

In [14]:
x[::1]

array([3, 2, 1])

In [15]:
x[::-1]

array([1, 2, 3])

In [16]:
x[::-2]

array([1, 3])

In [17]:
np.arange(3)

array([0, 1, 2])

In [18]:
np.arange(3,6)

array([3, 4, 5])

In [19]:
np.arange(1,-3,-20)

array([1])

In [20]:
np.arange(1,3.5,20)

array([1.])

In [21]:
np.arange(1,20,3.5)

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5])

In [22]:
np.array(2**np.arange(0,11))

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [23]:
np.array(3*np.ones(9))

array([3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [24]:
x = 3*np.ones(9)+np.array([1])

In [25]:
x

array([4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [29]:
lit = list(range(9))

In [30]:
lit = 3*lit

In [31]:
lit

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8]

In [32]:
lit = 9*[3]

In [33]:
lit

[3, 3, 3, 3, 3, 3, 3, 3, 3]

In [34]:
lit+=[1]

In [35]:
lit

[3, 3, 3, 3, 3, 3, 3, 3, 3, 1]

In [36]:
np.array(lit)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 1])

In [ ]:
import scikit-learn

In [ ]:
a

In [ ]:
lit

In [1]:
x

NameError: name 'x' is not defined